version: "3"

networks:
  analytics-net:
    external: true

services:
  kudu-master:
    image: apache/kudu:latest
    container_name: kudu-master
    ports:
      - "7051:7051"
      - "8051:8051"
    command: ["master"]
    volumes:
      - kudu-master:/var/lib/kudu
    networks:
          - analytics-net
    environment:
      - KUDU_MASTERS=kudu-master
      - >
        MASTER_ARGS=--fs_wal_dir=/var/lib/kudu/master
        --rpc_bind_addresses=0.0.0.0:7051
        --rpc_advertised_addresses=kudu-master:7051
        --webserver_port=8051
        --webserver_advertised_addresses=kudu-master:8051
        --webserver_doc_root=/opt/kudu/www
        --stderrthreshold=0
        --use_hybrid_clock=false
    restart: always
  kudu-tserver:
    image: apache/kudu:latest
    container_name: kudu-tserver
    depends_on:
      - kudu-master
    ports:
      - "7050:7050"
      - "8050:8050"
    command: ["tserver"]
    volumes:
      - kudu-tserver:/var/lib/kudu
    networks:
      - analytics-net
    environment:
    - KUDU_MASTERS=kudu-master
    - >
      TSERVER_ARGS=--fs_wal_dir=/var/lib/kudu/tserver
      --rpc_bind_addresses=0.0.0.0:7050
      --rpc_advertised_addresses=kudu-tserver:7050
      --webserver_port=8050
      --webserver_advertised_addresses=kudu-tserver:8050
      --webserver_doc_root=/opt/kudu/www
      --stderrthreshold=0
      --use_hybrid_clock=false
    restart: always
volumes:
  kudu-master:
  kudu-tserver:
