apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: prometheus-scaledobject
  namespace: monitoring
  labels:
    name: load-requests
spec:
  scaleTargetRef:
    name: load-requests
  pollingInterval: 15  # Optional. Default: 30 seconds
  cooldownPeriod:  30 # Optional. Default: 300 seconds
  minReplicaCount: 0   # Optional. Default: 0
  maxReplicaCount: 10 # Optional. Default: 100
  triggers:
  - type: prometheus
    metadata:
      # Required
      serverAddress: http://10.105.43.94:8080
      metricName: container_memory_working_set_bytes
      threshold: '1000'
      query: sum(container_memory_working_set_bytes{container="load-requests", namespace="monitoring"})/1000000
