kind: Service
apiVersion: v1
metadata:
  name: spark-master
spec:
  type: ClusterIP
  ports:
    - name: webui
      port: 8080
      targetPort: 8080
    - name: spark
      port: 7077
      targetPort: 7077
  selector:
    app: spark-master
