version: '3.7'

networks:
  analytics-net:
    external: true

services:
  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis:/data
    networks: 
      - analytics-net

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: superset
    volumes:
      - postgres:/var/lib/postgresql/data
    networks: 
      - analytics-net

  superset:
    build: .
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "8089:8088"
    volumes:
      - ./superset_config.py:/etc/superset/superset_config.py
      - ./env:/etc/superset/.env
    env_file: ./env
    networks: 
      - analytics-net

volumes:
  postgres:
  redis:
