version: "3"


networks:
  analytics-net:
    external: true

services:
  zeppelin:
    # image: apache/zeppelin:0.9.0
    build: 
      dockerfile: ./Dockerfile
      context: .
    networks:
      - analytics-net
    volumes:
      - ./spark-source/spark-3.0.0-bin-hadoop3.2:/spark
      - ../../geojson:/geojson
      - ./notebook:/opt/zeppelin/notebook
    ports:
      - "10088:8080"
    restart: always
